"""Build an attributed, grouped corpus from pinned local source repositories.

Reads source as text; never imports or executes it. Existing output directories
are refused. Every selected tracked path is accounted for in provenance.jsonl.
"""
from __future__ import annotations

import argparse
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import time
from urllib.parse import quote


SOURCES = {
    "cpython": {"url": "https://github.com/python/cpython",
                "scopes": (("Lib", ".py"), ("Doc", ".rst"))},
    "rust": {"url": "https://github.com/rust-lang/rust", "scopes": (("library", ".rs"),)},
    "mathlib4": {"url": "https://github.com/leanprover-community/mathlib4",
                 "scopes": (("Mathlib", ".lean"),)},
}
EXCLUDED_DIRS = {"vendor", "vendored", "third_party", "third-party", "external",
                 "fixtures", "fixture", "testdata", "test_data", "__pycache__",
                 "node_modules", "target", "_build", "build", ".lake"}
BENCHMARK = re.compile(r"(?<![A-Za-z0-9])(?:human[_-]?eval|mbpp|code[_-]?contests|apps)(?![A-Za-z0-9])", re.I)
GENERATED = re.compile(r"(?im)^[ \t]*(?://|#|/\*|\*|--|\.\.)?[ \t]*"
                       r"(?:[rubf]{0,2}(?:\"{3}|'{3})[ \t]*)?"
                       r"(?:@generated\b|this (?:file|code) (?:is|was) (?:automatically )?generated\b|"
                       r"automatically generated\b|generated by\b|do not edit\b|"
                       r"Python Character Mapping Codec [^\r\n]*\bgenerated from\b)")
SPDX = re.compile(r"SPDX-License-Identifier:\s*([^\r\n]+)")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def normalized_hash(text: str) -> str:
    # Preserve indentation and tokens. Only line endings, trailing line spaces,
    # and surrounding blank space are normalized for duplicate detection.
    normalized = "\n".join(line.rstrip() for line in text.splitlines()).strip()
    return sha256(normalized.encode("utf-8"))


def git(root: Path, *args: str) -> bytes:
    result = subprocess.run(["git", "-C", str(root), *args], capture_output=True, check=False)
    if result.returncode:
        raise ValueError(f"git inspection failed for {root.name}: {' '.join(args)}")
    return result.stdout


def selected(source: str, path: str) -> bool:
    p = Path(path)
    return any(p.parts[0] == directory and p.suffix == suffix
               for directory, suffix in SOURCES[source]["scopes"])


def path_exclusion(path: str) -> str | None:
    parts = [part.lower() for part in Path(path).parts]
    if any(part in EXCLUDED_DIRS for part in parts):
        return "vendored-generated-or-fixture-directory"
    if "data" in parts and any(part == "test" or part == "tests" or part.startswith("test_") for part in parts):
        return "test-fixture-data"
    if BENCHMARK.search(path):
        return "benchmark-name-in-path"
    return None


def module_stem(name: str) -> str:
    name = name.rsplit(".", 1)[0] if "." in name else name
    return name.removeprefix("test_").lstrip("_").split(".", 1)[0]


def module_family(source: str, path: str) -> str:
    parts = Path(path).parts
    if source == "cpython":
        if parts[0] == "Lib":
            offset = 2 if len(parts) > 2 and parts[1] == "test" else 1
            family = module_stem(parts[offset])
            if family.startswith("collections_"):
                family = "collections"
        elif len(parts) > 2 and parts[1] == "library":
            family = module_stem(parts[2])
            family = {"functions": "builtins", "stdtypes": "builtins",
                      "exceptions": "builtins", "constants": "builtins"}.get(family, family)
        else:
            family = "docs/" + (parts[1] if len(parts) > 2 else "root")
        family = {"httplib": "http", "urlparse": "urllib", "urllib2": "urllib"}.get(family, family)
        for prefix in ("xml", "email", "importlib", "asyncio", "sqlite3", "http", "logging", "pathlib"):
            if family.startswith((prefix + "_", prefix + "-")):
                family = prefix
                break
        return source + ":" + family
    if source == "rust":
        crate = "core" if parts[1] == "coretests" else parts[1]
        rest = list(parts[2:])
        if rest and rest[0] in ("src", "tests", "benches"):
            rest.pop(0)
        family = module_stem(rest[0]) if rest else "root"
        if family in ("lib", "mod", "main"):
            family = "root"
        # Test files commonly add a case suffix to the implementation module.
        for prefix in ("net", "sync", "io", "fmt", "num", "iter", "slice", "str", "array", "vec", "string"):
            if family.startswith(prefix + "_"):
                family = prefix
                break
        return f"rust:{crate}/{family}"
    # A namespace file and the directory below it share a family.
    namespace = [Path(part).stem for part in parts[1:3]]
    return "mathlib4:" + "/".join(namespace)


def choose_split(group: str, seed: int, validation_fraction: float) -> str:
    value = int(sha256(f"{seed}\0{group}".encode()), 16)
    return "validation" if value < int(validation_fraction * (1 << 256)) else "train"


def source_kind(source: str, path: str) -> str:
    parts = Path(path).parts
    if source == "mathlib4":
        return "proof"
    if Path(path).suffix == ".rst":
        return "documentation"
    if (source == "cpython" and "test" in parts) or "tests" in parts or "benches" in parts or "coretests" in parts:
        return "test"
    return "code"


def inspect_source(base: Path, name: str) -> tuple[dict, list[tuple[str, str]]]:
    root = base / name
    revision = git(root, "rev-parse", "HEAD").decode().strip()
    if not re.fullmatch(r"[0-9a-f]{40,64}", revision):
        raise ValueError(f"{name}: invalid resolved revision")
    origin = git(root, "remote", "get-url", "origin").decode().strip().removesuffix(".git").rstrip("/")
    if origin != SOURCES[name]["url"]:
        raise ValueError(f"{name}: origin must match the declared official source URL")
    if git(root, "diff", "--name-only", "HEAD").strip():
        raise ValueError(f"{name}: tracked files differ from the pinned revision")
    entries = []
    licenses = []
    for raw in git(root, "ls-files", "--stage", "-z").split(b"\0"):
        if not raw:
            continue
        metadata, raw_path = raw.split(b"\t", 1)
        mode, _blob, stage = metadata.decode().split()
        if stage != "0":
            raise ValueError(f"{name}: unresolved index entries")
        path = raw_path.decode("utf-8")
        if selected(name, path):
            entries.append((path, mode))
        p = Path(path)
        is_notice = re.match(r"(?i)^(?:licen[sc]e(?:[._-].*)?|copying(?:[._-].*)?|copyright(?:[._-].*)?|notice(?:[._-].*)?)$", p.name)
        if (is_notice and mode in ("100644", "100755") and (root / p).is_file()
                and not any(x.lower() in EXCLUDED_DIRS for x in p.parts)):
            licenses.append({"path": path, "sha256": sha256((root / p).read_bytes())})
    root_licenses = [item for item in licenses if len(Path(item["path"]).parts) == 1
                     and Path(item["path"]).name.lower().startswith(("license", "licence", "copying"))
                     and Path(item["path"]).suffix.lower() not in (".json", ".toml", ".yaml", ".yml")
                     and (root / item["path"]).stat().st_size > 0]
    if not root_licenses:
        raise ValueError(f"{name}: a tracked root license is required; refusing undocumented source")
    if not entries:
        raise ValueError(f"{name}: no tracked files match the declared source selection")
    return {"source": name, "source_url": origin, "revision": revision,
            "scopes": [{"directory": d, "suffix": s} for d, s in SOURCES[name]["scopes"]],
            "license_snapshots": licenses}, sorted(entries)


def inspect_file(args) -> tuple[dict, str | None]:
    base, source, info, path, mode, seed, fraction = args
    group = module_family(source, path)
    record = {"source": source, "source_url": info["source_url"], "revision": info["revision"],
              "path": path, "url": f"{info['source_url']}/blob/{info['revision']}/{quote(path, safe='/')}",
              "group": group, "split": choose_split(group, seed, fraction), "included": False,
              "license_snapshots": [f"licenses/{source}/{item['path']}" for item in info["license_snapshots"]
                                    if Path(item["path"]).parent in (Path("."), *Path(path).parents)],
              "source_kind": source_kind(source, path)}
    reason = path_exclusion(path)
    if mode not in ("100644", "100755"):
        reason = "nonregular-git-entry"
    file = base / source / path
    if file.is_symlink():
        reason = "symlink"
    if reason:
        record["reason"] = reason
        return record, None
    if not file.is_file():
        raise ValueError(f"{source}/{path}: selected tracked file missing from local checkout")
    data = file.read_bytes()
    record.update(sha256=sha256(data), byte_count=len(data))
    if b"\0" in data:
        record["reason"] = "binary-nul"
        return record, None
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        record["reason"] = "non-utf8"
        return record, None
    record.update(char_count=len(text), line_count=len(text.splitlines()),
                  normalized_sha256=normalized_hash(text),
                  spdx_identifiers=sorted(set(SPDX.findall(text))))
    if not text.strip():
        record["reason"] = "empty"
    elif BENCHMARK.search(text):
        record["reason"] = "benchmark-name-in-content"
    elif GENERATED.search("\n".join(text.splitlines()[:80])):
        record["reason"] = "generated-header"
    else:
        record["included"] = True
        return record, text
    return record, None


def build(source_root: Path, out: Path, *, validation_fraction=0.1, seed=1337, workers=8) -> dict:
    if not 0 < validation_fraction < 1 or workers < 1:
        raise ValueError("validation fraction must be between zero and one; workers must be positive")
    if out.exists():
        raise ValueError("output already exists; choose a new output directory")
    out.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix=f".{out.name}.building-", dir=out.parent))
    try:
        sources, jobs = {}, []
        for name in sorted(SOURCES):
            info, entries = inspect_source(source_root, name)
            sources[name] = info
            for item in info["license_snapshots"]:
                target = stage / "licenses" / name / item["path"]
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source_root / name / item["path"], target)
            jobs.extend((source_root, name, info, path, mode, seed, validation_fraction)
                        for path, mode in entries)
        lock = {"format": 1, "sources": sources, "seed": seed,
                "requested_validation_fraction": validation_fraction,
                "builder_sha256": sha256(Path(__file__).read_bytes()),
                "normalization": "Unicode text splitlines, trailing line whitespace removed, outer whitespace stripped",
                "split_rule": "sha256(seed + NUL + module family), one split per whole family",
                "duplicate_rule": "first selected source/path wins; global exact and normalized duplicate exclusion"}
        (stage / "sources-lock.json").write_text(json.dumps(lock, indent=2, sort_keys=True) + "\n")
        counts = {split: Counter() for split in ("train", "validation")}
        groups = {split: set() for split in counts}
        hashes = {split: set() for split in counts}
        normalized = {split: set() for split in counts}
        reasons, by_source = Counter(), {name: Counter() for name in sources}
        by_kind = {kind: Counter() for kind in ("code", "test", "documentation", "proof")}
        seen_exact, seen_normalized = {}, {}
        with (stage / "train.txt").open("w", encoding="utf-8", newline="\n") as train, \
                (stage / "validation.txt").open("w", encoding="utf-8", newline="\n") as val, \
                (stage / "provenance.jsonl").open("w", encoding="utf-8") as provenance, \
                ThreadPoolExecutor(max_workers=workers) as executor:
            streams = {"train": train, "validation": val}
            for record, text in executor.map(inspect_file, jobs):
                source = record["source"]
                by_source[source]["selected_files"] += 1
                by_kind[record["source_kind"]]["selected_files"] += 1
                key = source + "/" + record["path"]
                if record["included"]:
                    prior = seen_exact.get(record["sha256"])
                    reason = "exact-duplicate"
                    if prior is None:
                        prior = seen_normalized.get(record["normalized_sha256"])
                        reason = "normalized-duplicate"
                    if prior is not None:
                        record.update(included=False, reason=reason, duplicate_of=prior)
                if record["included"]:
                    split = record["split"]
                    seen_exact[record["sha256"]] = key
                    seen_normalized[record["normalized_sha256"]] = key
                    streams[split].write(f"\n\n# file: {key}\n")
                    streams[split].write(text)
                    if not text.endswith("\n"):
                        streams[split].write("\n")
                    counts[split].update(files=1, source_bytes=record["byte_count"], chars=record["char_count"],
                                         lines=record["line_count"])
                    groups[split].add(record["group"])
                    hashes[split].add(record["sha256"])
                    normalized[split].add(record["normalized_sha256"])
                    by_source[source].update(included_files=1, source_bytes=record["byte_count"])
                    by_kind[record["source_kind"]].update(included_files=1, source_bytes=record["byte_count"])
                else:
                    reasons[record["reason"]] += 1
                    by_source[source]["excluded_files"] += 1
                    by_kind[record["source_kind"]]["excluded_files"] += 1
                provenance.write(json.dumps(record, sort_keys=True, ensure_ascii=False) + "\n")
        if not all(counts[split]["files"] for split in counts):
            raise ValueError("group assignment produced an empty split; choose another seed or validation fraction")
        for name, values in (("module families", groups), ("exact hashes", hashes), ("normalized hashes", normalized)):
            if values["train"] & values["validation"]:
                raise AssertionError(f"cross-split overlap in {name}")
        for source in sources:
            # Detect a source checkout changing while the files were read.
            if git(source_root / source, "rev-parse", "HEAD").decode().strip() != sources[source]["revision"] or \
                    git(source_root / source, "diff", "--name-only", "HEAD").strip():
                raise ValueError(f"{source}: checkout changed during the build")
        total_bytes = sum(value["source_bytes"] for value in counts.values())
        report = {"sources": by_source, "source_kinds": by_kind, "splits": {k: {**v, "groups": len(groups[k]),
                   "corpus_bytes": (stage / ("train.txt" if k == "train" else "validation.txt")).stat().st_size}
                   for k, v in counts.items()}, "excluded": reasons,
                  "selected_files": len(jobs), "included_files": sum(c["files"] for c in counts.values()),
                  "included_source_bytes": total_bytes,
                  "achieved_validation_byte_fraction": counts["validation"]["source_bytes"] / total_bytes,
                  "cross_split_group_overlap": 0, "cross_split_exact_overlap": 0,
                  "cross_split_normalized_overlap": 0, "truncated_files": 0,
                  "artifacts": {name: sha256((stage / name).read_bytes()) for name in
                                ("train.txt", "validation.txt", "provenance.jsonl", "sources-lock.json")}}
        (stage / "quality.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
        write_card(stage, lock, report)
        stage.rename(out)
        return report
    except BaseException:
        shutil.rmtree(stage)
        raise


def write_card(stage: Path, lock: dict, report: dict):
    lines = ["# Source pretraining corpus", "", "This is plain-text causal-language-model pretraining data.",
             "No task prompts, preference pairs, or chat templates are introduced.", "", "## Provenance", "",
             "All included text is copied from tracked files in the pinned official repositories below.",
             "The full source text, including its copyright and license headers, is preserved.", ""]
    for name, info in lock["sources"].items():
        lines.append(f"- {name}: {info['source_url']}, revision `{info['revision']}`.")
    lines += ["", "`provenance.jsonl` records every selected path, its source, revision, family, split,",
              "inclusion decision, content hashes when read, byte/character/line counts, detected SPDX",
              "identifiers, and ancestor/root license snapshot paths. `sources-lock.json` pins the inputs.",
              "Root licenses and available tracked nested license/copyright/notice files are copied under `licenses/`.",
              "The builder refuses missing root-license evidence. These snapshots document provenance;",
              "they do not establish one license for every file or determine obligations for a model.",
              "", "## Counts and split", "", "| split | files | module families | source bytes | corpus bytes |",
              "|---|---:|---:|---:|---:|"]
    for split, stats in report["splits"].items():
        lines.append(f"| {split} | {stats['files']} | {stats['groups']} | {stats['source_bytes']} | {stats['corpus_bytes']} |")
    lines += ["", "| kind | included files | source bytes |", "|---|---:|---:|"]
    for kind, stats in report["source_kinds"].items():
        lines.append(f"| {kind} | {stats.get('included_files', 0)} | {stats.get('source_bytes', 0)} |")
    lines += ["", f"Requested validation fraction: {lock['requested_validation_fraction']}; measured source-byte fraction: "
              f"{report['achieved_validation_byte_fraction']:.6f}; seed: {lock['seed']}.",
              "A stable hash assigns whole module families to splits. CPython library/tests/module docs",
              "share module stems; Rust implementation/test modules share crate/module families; Mathlib",
              "uses the first two namespaces. This is broad structural grouping, not a guarantee that",
              "every semantically related file is in one family. Hash assignment need not hit 10% by bytes.",
              "", "## Deduplication and exclusions", "",
              "Global exact-byte and normalized-text deduplication retains the first source/path in sorted",
              "order. Normalization changes only line endings, trailing line whitespace, and outer whitespace",
              "for comparison; the corpus retains the original text. It is not semantic deduplication.",
              "Cross-split family, exact-hash, and normalized-hash overlaps are all zero.",
              "No file is truncated. Binary/NUL, invalid UTF-8, empty, generated-header, vendored/fixture",
              "directory, and benchmark-name matches are excluded explicitly. HumanEval, MBPP, APPS, and",
              "CodeContests names are screened in paths and content, case-insensitively. This conservative",
              "APPS name screen may also exclude ordinary prose using that word.", ""]
    lines += [f"- {reason}: {count}" for reason, count in sorted(report["excluded"].items())]
    lines += ["", "## Origin, tokenization, and packing", "",
              "100% of included source bytes are external repository material; 0% was generated by this",
              "training pipeline. The authorship process of upstream text is not inferred from that ratio.",
              "No tokenizer, chat template, loss mask, or sequence packing is applied by this builder.",
              "A downstream causal pretraining run learns from all source tokens. Fit any learned tokenizer",
              "on `train.txt` only and pass `validation.txt` explicitly; do not resplit the joined corpus.",
              "Document boundaries use the existing `# file:` convention. Token counts, model context,",
              "batch packing, and training readiness require the later tokenizer/training audit.",
              "", "`quality.json` contains all counts and artifact SHA256 values. This corpus has not been",
              "evaluated for semantic contamination against held-out tasks beyond the named filters.", ""]
    (stage / "DATASET.md").write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--validation-fraction", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--workers", type=int, default=8)
    args = parser.parse_args()
    start = time.monotonic()
    report = build(args.source_root, args.out, validation_fraction=args.validation_fraction,
                   seed=args.seed, workers=args.workers)
    print(json.dumps({"selected_files": report["selected_files"], "included_files": report["included_files"],
                      "included_source_bytes": report["included_source_bytes"],
                      "splits": report["splits"], "excluded": report["excluded"],
                      "seconds": round(time.monotonic() - start, 3)}, indent=2))


if __name__ == "__main__":
    main()
