"""Fit a training-only tokenizer and inspect reproducible source-corpus windows.

Run after build_source_corpus.py. This reads data only; source is never executed.
The saved tokenizer is shared by every arm of the pretraining comparison.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import random

from data import BPETokenizer, tokenizer_fingerprint


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def audit(corpus: Path, out: Path, *, vocab_size=8192, context=2048, seed=1337) -> dict:
    if out.exists():
        raise ValueError("audit output already exists; use a new directory")
    if context < 1:
        raise ValueError("context must be positive")
    quality = json.loads((corpus / "quality.json").read_text())
    raw = {}
    for name in ("train.txt", "validation.txt", "provenance.jsonl", "sources-lock.json"):
        content = (corpus / name).read_bytes()
        if digest(content) != quality["artifacts"][name]:
            raise ValueError(f"source artifact changed: {name}")
        raw[name] = content
    by_kind, by_source = Counter(), Counter()
    families = {"train": set(), "validation": set()}
    exact = {"train": set(), "validation": set()}
    normalized = {"train": set(), "validation": set()}
    for line in raw["provenance.jsonl"].decode("utf-8").splitlines():
        record = json.loads(line)
        if not record["included"]:
            continue
        split = record["split"]
        families[split].add(record["group"])
        exact[split].add(record["sha256"])
        normalized[split].add(record["normalized_sha256"])
        by_kind[record["source_kind"]] += record["byte_count"]
        by_source[record["source"]] += record["byte_count"]
    for label, groups in (("family", families), ("exact", exact), ("normalized", normalized)):
        if groups["train"] & groups["validation"]:
            raise ValueError(f"cross-split {label} overlap")
    texts = {name: raw[name + ".txt"].decode("utf-8") for name in ("train", "validation")}
    print("Fitting BPE on the frozen training partition", flush=True)
    tok = BPETokenizer.from_text(texts["train"], vocab_size=vocab_size)
    stats = {}
    examples = []
    for name, text in texts.items():
        ids = tok.encode(text)
        if tok.decode(ids) != text:
            raise ValueError(f"tokenizer changed {name} text")
        if len(ids) <= context:
            raise ValueError(f"{name} has too few tokens for the requested context")
        stats[name] = {"sha256": digest(raw[name + ".txt"]), "chars": len(text),
                       "bytes": len(raw[name + ".txt"]), "tokens": len(ids),
                       "roundtrip": True, "tokens_per_byte": len(ids) / len(raw[name + ".txt"])}
        if name == "train":
            rng = random.Random(seed)
            # Spread windows across all of the sorted sources, rather than
            # accidentally inspecting only the first source's beginning.
            for i in range(10):
                lo = i * (len(ids) - context) // 10
                hi = (i + 1) * (len(ids) - context) // 10
                start = rng.randint(lo, hi)
                examples.append({"index": i, "start_token": start,
                                 "tokens": context, "text": tok.decode(ids[start:start + context])})
        print(json.dumps({"split": name, **stats[name]}), flush=True)
        del ids
    out.mkdir(parents=True)
    tok.save(out / "tokenizer.json")
    report = {"corpus_artifacts": quality["artifacts"], "tokenizer_fingerprint": tokenizer_fingerprint(tok),
              "tokenizer_file_sha256": digest((out / "tokenizer.json").read_bytes()),
              "vocab_size": tok.vocab_size, "requested_vocab_size": vocab_size,
              "context": context, "window_seed": seed, "splits": stats,
              "source_bytes_by_kind": by_kind, "source_bytes_by_source": by_source,
              "cross_split_family_overlap": 0, "cross_split_exact_overlap": 0,
              "cross_split_normalized_overlap": 0, "training_windows": len(examples),
              "authorship": "external source repositories; no text generated by this pipeline",
              "loss_mask": "all tokens for causal pretraining; no chat template"}
    (out / "audit.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    (out / "windows.jsonl").write_text("\n".join(json.dumps(e, ensure_ascii=False) for e in examples) + "\n")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--corpus", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--vocab-size", type=int, default=8192)
    parser.add_argument("--context", type=int, default=2048)
    parser.add_argument("--seed", type=int, default=1337)
    args = parser.parse_args()
    print(json.dumps(audit(args.corpus, args.out, vocab_size=args.vocab_size,
                           context=args.context, seed=args.seed), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
