#!/usr/bin/env python3
"""mbpp_gate_order.py -- which gate to open next for the MBPP-DFY 164, asked
of both instruments.

ROADMAP WS-16.2 wants 82 of the 164 MBPP-DFY programs lifted and verified by
seven kernels. WS-13.1 says to measure the gate order over those 164 alone
before opening a gate for them.

Half of that was already done and the roadmap had not noticed:
`coverage_census.py` runs its greedy curve on the MBPP-DFY family and
`COVERAGE-dafnybench.md` carries the twenty steps. But 12.4 replaced the
census as the authority on fragment membership ("a program is in the fragment
when it LIFTS into a t task and seven kernels verify it"), and on the LIFTER
side nothing is broken out by family at all: `LIFTER-785.md` has no family
table and `lift_census.py` drops the `family` field on the way in.

So this asks both, side by side:

  CENSUS  the lexical greedy curve over the 164, reusing
          `coverage_census.greedy` unchanged on a filtered record list. A gap
          SET per program, so the curve is a real "open this next" walk.
  LIFTER  what the lifter actually did to the same 164, read from the run's
          own `out/lift/*.outcome.json` markers.

They are not the same measurement and the difference is the point. The census
knows every gap a program has; the lifter stops at the FIRST construct it
refuses and never looks further, so its tally is a histogram of first
refusals, not a gap set. A lifter first-refusal count is therefore a LOWER
bound on what opening that gate would unlock: clearing div-mod frees only the
programs whose sole remaining objection was div-mod.

    python3 mbpp_gate_order.py
    python3 mbpp_gate_order.py --markdown out/mbpp-gate-order.md

Standard library only, no dafny. Needs census.json (via corpora.py) and, for
the lifter half, a completed run under out/lift.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import corpora            # noqa: E402
import coverage_census    # noqa: E402
import mbpp_dfy           # noqa: E402

DEFAULT_LIFT = HERE / "out" / "lift"
BAR = 82   # WS-16.2's coverage half of the 1.0 bar


def census_records():
    """The 164 MBPP-DFY records out of census.json."""
    if not corpora.CENSUS_JSON.exists():
        return []
    recs = json.loads(corpora.CENSUS_JSON.read_text(encoding="utf-8"))
    return [r for r in recs
            if mbpp_dfy.DFY_NAME_RE.match(r.get("file", ""))]


def lifter_verdicts(lift_dir: Path):
    """{file: [verdict, ...]} for the MBPP-DFY files in a lifter run.

    One entry per gradable method, plus one for a file-level refusal, which
    is how LIFTER-785.md counts too.
    """
    out: dict[str, list[str]] = {}
    if not lift_dir.exists():
        return out
    for m in sorted(lift_dir.glob("*.outcome.json")):
        stem = m.name[: -len(".outcome.json")]
        if not mbpp_dfy.DFY_NAME_RE.match(stem + ".dfy"):
            continue
        rec = json.loads(m.read_text(encoding="utf-8"))
        verdicts = []
        for key in ("parse_refusal", "resolve_refusal"):
            r = rec.get(key)
            if r:
                verdicts.append("refused:" + (r.get("reason") or key))
        for e in rec.get("methods", []):
            if e.get("checked"):
                verdicts.append("lifted")
            else:
                r = e.get("refusal") or {}
                verdicts.append("refused:" + (r.get("reason") or "unchecked"))
        out[stem + ".dfy"] = verdicts
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--lift", type=Path, default=DEFAULT_LIFT)
    ap.add_argument("--markdown", type=Path, default=None)
    args = ap.parse_args(argv)

    recs = census_records()
    if not recs:
        print("no census.json at %s. %s"
              % (corpora.CENSUS_JSON, corpora.why_missing(corpora.CENSUS_JSON)))
        return 1

    lines = []

    def w(s=""):
        print(s)
        lines.append(s)

    gradable = [r for r in recs
                if r.get("has-method") and r.get("method-with-ensures")]
    in_frag = sum(1 for r in recs if r.get("in_fragment"))
    w("# The MBPP-DFY 164: which gate to open next, asked of both instruments")
    w()
    w("Generated by `t/mbpp_gate_order.py`. WS-16.2 wants 82 of these 164")
    w("lifted and verified by seven kernels; WS-13.1 asks for the gate order")
    w("over them alone before opening a gate for them. The census half reuses")
    w("`coverage_census.greedy` unchanged, so it reproduces the MBPP section of")
    w("`COVERAGE-dafnybench.md`; the lifter half is read from a completed run.")
    w()
    w("MBPP-DFY: %d programs, %d gradable, %d lexically in fragment"
      % (len(recs), len(gradable), in_frag))
    w()

    w("## The census curve (gap sets, so a real gate walk)")
    w()
    w("| step | gate | newly unlocked | cumulative | of %d |" % len(gradable))
    w("|---|---|---:|---:|---:|")
    hit = None
    for i, (gate, k, cum) in enumerate(coverage_census.greedy(recs), 1):
        w("| %d | %s | %d | %d | %.1f%% |"
          % (i, gate, k, cum, 100 * cum / max(1, len(gradable))))
        if hit is None and cum >= BAR:
            hit = (i, gate, cum)
    w()
    if hit:
        w("Reaches WS-16.2's bar of %d at step %d, on opening `%s` (%d)."
          % (BAR, hit[0], hit[1], hit[2]))
    else:
        w("Never reaches WS-16.2's bar of %d." % BAR)

    verdicts = lifter_verdicts(args.lift)
    if not verdicts:
        w()
        w("No lifter run under %s, so the lifter half is unmeasured here."
          % args.lift)
    else:
        rows = [v for vs in verdicts.values() for v in vs]
        tally = Counter(rows)
        lifted = tally.get("lifted", 0)
        w()
        w("## What the lifter actually did to the same programs")
        w()
        w("%d files with a record, %d method rows, %d lifted."
          % (len(verdicts), len(rows), lifted))
        w()
        w("| first refusal | rows |")
        w("|---|---:|")
        for reason, n in tally.most_common():
            if reason != "lifted":
                w("| %s | %d |" % (reason.replace("refused:", ""), n))
        w()
        w("A first-refusal count is a LOWER bound on what opening that gate")
        w("buys: the lifter stops at the first construct it cannot take, so a")
        w("program counted under one gate may be blocked by others behind it.")

        # Where the two instruments part.
        lex = {}
        for r in recs:
            lex[r["file"]] = set(r.get("gaps") or [])
        both = [f for f in verdicts if f in lex]
        lifted_files = [f for f in both
                        if any(v == "lifted" for v in verdicts[f])]
        census_clean = [f for f in both if not lex[f]]
        w()
        w("## Where they part")
        w()
        w("| | count |")
        w("|---|---:|")
        w("| files with both a census record and a lifter record | %d |" % len(both))
        w("| the census calls in fragment (no gaps) | %d |" % len(census_clean))
        w("| the lifter lifted at least one method | %d |" % len(lifted_files))
        w("| lifted although the census named a gap | %d |"
          % len([f for f in lifted_files if lex[f]]))
        w("| census-clean but nothing lifted | %d |"
          % len([f for f in census_clean if f not in lifted_files]))

    if args.markdown:
        args.markdown.parent.mkdir(parents=True, exist_ok=True)
        args.markdown.write_text("\n".join(lines) + "\n", encoding="utf-8",
                                 newline="\n")
        print()
        print("wrote %s" % args.markdown)
    return 0


if __name__ == "__main__":
    sys.exit(main())
