#!/usr/bin/env python3
"""mbpp_lifter_census.py -- the MBPP-DFY 164, one row per program, three
instruments joined: the lexical census (`COVERAGE-mbpp-dfy.md`'s source),
the lifter's own outcome markers (`LIFTER-785.md`'s source, filtered to the
164), and the fifteenth sweep's agreement table (`COVERAGE-lifted-785.md`).

ROADMAP 13.1's open half: measure the gate order over the 164 on the LIFTER
side before opening a gate for them, and say where it parts from the lexical
one. `mbpp_gate_order.py` already runs the lexical greedy curve and tallies
the lifter's first-refusal histogram side by side; this module adds the
per-program join and a second greedy curve, restricted to the vocabulary
ROADMAP 13.1 names for the lifter side: a lifter refusal name closed, or one
kernel's sole-blocked cells closed. It does NOT include lexical gates as
items -- those are the other curve's business, in `mbpp_gate_order.py` and
`COVERAGE-mbpp-dfy.md` -- so its population is exactly the programs the
census already calls "in fragment" (gap set empty). A program still lexically
out needs a lexical gate opened first and is out of scope for this curve;
its row says so.

    python3 mbpp_lifter_census.py
    python3 mbpp_lifter_census.py --out COVERAGE-mbpp-dfy-lifter.md

Standard library only, no dafny. Reads three committed/on-disk sources, none
of them a kernel run:

  - census.json (via corpora.py, same source `mbpp_gate_order.py` reads)
  - a completed lifter run's `out/lift/*.outcome.json` markers (default
    `t/out/lift`; pass --lift to point at another one, such as the Dell's
    full 785 run, which this worktree does not carry)
  - `COVERAGE-lifted-785.md`, the fifteenth sweep's own committed table
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import coverage_census      # noqa: E402
import mbpp_gate_order      # noqa: E402
import mbpp_dfy             # noqa: E402

DEFAULT_LIFT = HERE / "out" / "lift"
DEFAULT_SWEEP = HERE / "COVERAGE-lifted-785.md"
BAR = 82

KERNEL_COLS = ("dafny", "verus", "spark", "framac", "lean", "rocq", "fstar")
SWEEP_ROW_RE = re.compile(r"^\|\s*(\S+)\s*\|(.+)\|\s*$")


def load_sweep(path: Path) -> dict[str, list[str]]:
    """label -> list of 7 raw cell strings ("real / twin"), from the
    committed agreement table. Only rows are read; the header is skipped by
    requiring the row to have exactly len(KERNEL_COLS) cells after the
    label."""
    out: dict[str, list[str]] = {}
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| dafny_synthesis_task_id_"):
            continue
        m = SWEEP_ROW_RE.match(line)
        if not m:
            continue
        label = m.group(1)
        cells = [c.strip() for c in m.group(2).split("|")]
        cells = [c for c in cells if c != ""] if False else cells
        if len(cells) != len(KERNEL_COLS):
            continue
        out[label] = cells
    return out


def sweep_label(file_stem: str, method: str) -> str:
    """`dafny-synthesis_task_id_101` + `KthElement` -> the row key
    `COVERAGE-lifted-785.md` uses: `dafny_synthesis_task_id_101__kthElement`
    (first hyphen to underscore, method's first letter lowered). Verified
    against the committed table for tasks 101, 14 and 234 by hand."""
    head = file_stem.replace("-", "_", 1)
    m = (method[:1].lower() + method[1:]) if method else method
    return f"{head}__{m}"


def blocking_kernels(cells: list[str]) -> list[str]:
    """Kernel names, in KERNEL_COLS order, whose cell is not the agreement
    reading `verified / refuted`."""
    return [k for k, c in zip(KERNEL_COLS, cells) if c != "verified / refuted"]


def census_greedy_assignment(recs) -> dict[str, str]:
    """file -> the gate that closes it, replaying `coverage_census.greedy`'s
    OWN walk (not just consulting its current `GAPS` list): census.json was
    generated by an earlier `coverage_census.py`, so some programs carry gap
    names (`string-char`, `nested-seq`, `multi-return`) the CURRENT
    `DETECTORS` table has since split (`string-lib`, `nested-seq-string` /
    `-deep` / `-other`, `multi-return-arity`) and no longer lists in `GAPS`.
    `greedy`'s own fallback branch (open the most-common still-needed gap
    when no `GAPS` member unlocks anything) already copes with this -- it is
    how `COVERAGE-mbpp-dfy.md`'s table names `string-char` and `nested-seq`
    at all -- so this replays the SAME loop rather than filtering by `GAPS`,
    to stay a real disagreement-preserving reading rather than a second,
    silently-different one."""
    open_gates: set[str] = set()
    remaining = [p for p in recs if not p["in_fragment"]
                 and p.get("has-method") and p.get("method-with-ensures")]
    gate_of: dict[str, str] = {}
    while remaining:
        best, best_n = None, 0
        for gt in coverage_census.GAPS:
            if gt in open_gates:
                continue
            n = sum(1 for p in remaining if set(p["gaps"]) <= open_gates | {gt})
            if n > best_n:
                best, best_n = gt, n
        if best is None or best_n == 0:
            cnt = Counter(gt for p in remaining for gt in p["gaps"]
                          if gt not in open_gates)
            if not cnt:
                break
            best = cnt.most_common(1)[0][0]
        open_gates.add(best)
        unlocked = [p for p in remaining if set(p["gaps"]) <= open_gates]
        for p in unlocked:
            gate_of[p["file"]] = best
        remaining = [p for p in remaining if p not in unlocked]
    return gate_of


def lifter_status(file: str, verdicts: dict[str, list[str]]):
    """('lifted', [method names lifted]) / ('refused', first reason) /
    ('no-record', None), reading the SAME ordered verdict list
    `mbpp_gate_order.lifter_verdicts` builds (parse/resolve refusal first,
    then one entry per method in file order) -- so "first reason" here is
    the same first-refusal reading its histogram counts."""
    vs = verdicts.get(file)
    if not vs:
        return ("no-record", None)
    if any(v == "lifted" for v in vs):
        return ("lifted", None)
    first = vs[0]
    return ("refused", first[len("refused:"):] if first.startswith("refused:") else first)


def outcome_methods(file: str, lift_dir: Path) -> list[dict]:
    """The raw `methods` list from the one outcome.json, checked or not --
    every entry carries a `method` name even when refused."""
    import json
    stem = file[:-4] if file.endswith(".dfy") else file
    p = lift_dir / f"{stem}.outcome.json"
    if not p.exists():
        return []
    rec = json.loads(p.read_text(encoding="utf-8"))
    return rec.get("methods", [])


def lifted_methods(file: str, lift_dir: Path) -> list[str]:
    """Method names the outcome record actually checked, for building the
    sweep label."""
    return [e["method"] for e in outcome_methods(file, lift_dir) if e.get("checked")]


def program_name(file: str, lift_dir: Path) -> str:
    """The method name for this MBPP-DFY program, for the table's `name`
    column: the first method the outcome record names (checked or refused
    alike), so every row gets a real name rather than the shared family
    label. Falls back to the .dfy stem when there is no outcome record at
    all (should not happen over the 164; see the module's reproducibility
    note if it does)."""
    methods = outcome_methods(file, lift_dir)
    if methods:
        return methods[0]["method"]
    return file[:-4] if file.endswith(".dfy") else file


def build_rows(recs, verdicts, lift_dir: Path, sweep: dict[str, list[str]]):
    gate_of = census_greedy_assignment(recs)
    rows = []
    for r in sorted(recs, key=lambda r: int(mbpp_gate_order_task_id(r["file"]))):
        file = r["file"]
        task_id = mbpp_gate_order_task_id(file)
        gaps = set(r.get("gaps") or [])
        in_frag = bool(r.get("in_fragment"))
        lstat, lreason = lifter_status(file, verdicts)

        sweep_state, sweep_detail, label = "n/a", None, None
        if lstat == "lifted":
            methods = lifted_methods(file, lift_dir)
            for m in methods:
                cand = sweep_label(file[:-4], m)
                if cand in sweep:
                    label = cand
                    break
            if label is None:
                sweep_state = "not-swept"
            else:
                cells = sweep[label]
                blockers = blocking_kernels(cells)
                if not blockers:
                    sweep_state = "all-seven"
                else:
                    sweep_state = "blocked"
                    sweep_detail = {k: c for k, c in zip(KERNEL_COLS, cells)
                                     if k in blockers}

        rows.append({
            "task_id": task_id,
            "file": file,
            "name": program_name(file, lift_dir),
            "in_fragment": in_frag,
            "gaps": gaps,
            "primary_gap": gate_of.get(file),
            "lifter_status": lstat,
            "lifter_reason": lreason,
            "sweep_state": sweep_state,
            "sweep_detail": sweep_detail,
            "label": label,
        })
    return rows


def mbpp_gate_order_task_id(file: str) -> str:
    m = mbpp_dfy.DFY_NAME_RE.match(file)
    return m.group(1) if m else "?"


def next_move(row) -> str:
    if not row["in_fragment"]:
        g = row["primary_gap"]
        return f"lexical gate: {g}" if g else "lexical gate (unnamed)"
    if row["lifter_status"] == "refused":
        return f"lifter row: {row['lifter_reason']}"
    if row["lifter_status"] == "no-record":
        return "lifter: no record (re-run the lifter over this file)"
    if row["sweep_state"] == "all-seven":
        return "none (already all seven)"
    if row["sweep_state"] == "blocked":
        blockers = sorted(row["sweep_detail"])
        if len(blockers) == 1:
            return f"kernel: {blockers[0]}"
        return "kernel (co-blocked): " + "+".join(blockers)
    if row["sweep_state"] == "not-swept":
        return "sweep: not in COVERAGE-lifted-785.md (run the sweep)"
    return "?"


def greedy_lifter(rows):
    """The LIFTER-side greedy: population is the lexically-in-fragment rows
    only (gaps opening a lexical gate is out of scope here, that is
    `mbpp_gate_order.py`'s curve). Items are `lifter:<reason>` and
    `kernel:<name>`; a row's requirement set is a SINGLETON drawn from
    whichever tier applies (the lifter stops at its first refusal, so a
    lifter-refused row names one reason, a LOWER bound the same way
    `mbpp_gate_order.py`'s histogram is one; a lifted-but-blocked row names
    every kernel whose cell fell short, since all of them must clear)."""
    in_frag = [r for r in rows if r["in_fragment"]]
    covered0 = sum(1 for r in in_frag if r["sweep_state"] == "all-seven")
    reqs: dict[str, set[str]] = {}
    for r in in_frag:
        if r["sweep_state"] == "all-seven":
            continue
        if r["lifter_status"] == "refused":
            reqs[r["file"]] = {"lifter:" + r["lifter_reason"]}
        elif r["lifter_status"] == "no-record":
            reqs[r["file"]] = {"lifter:no-record"}
        elif r["sweep_state"] == "blocked":
            reqs[r["file"]] = {"kernel:" + k for k in r["sweep_detail"]}
        elif r["sweep_state"] == "not-swept":
            reqs[r["file"]] = {"not-swept"}

    open_items: set[str] = set()
    remaining = dict(reqs)
    covered = covered0
    steps = []
    while remaining:
        candidates = sorted({it for s in remaining.values() for it in s
                              if it not in open_items})
        best_item, best_ids = None, []
        for it in candidates:
            ids = [pid for pid, s in remaining.items() if s <= open_items | {it}]
            if len(ids) > len(best_ids):
                best_item, best_ids = it, ids
        if best_item is None:
            break
        open_items.add(best_item)
        for pid in best_ids:
            del remaining[pid]
        covered += len(best_ids)
        steps.append((best_item, len(best_ids), covered))
    return covered0, steps, list(remaining)


def groups(rows):
    lex_out = [r for r in rows if not r["in_fragment"]]
    lex_out_by_gate = Counter(r["primary_gap"] for r in lex_out)

    in_frag = [r for r in rows if r["in_fragment"]]
    refused = [r for r in in_frag if r["lifter_status"] == "refused"]
    refused_by_reason = Counter(r["lifter_reason"] for r in refused)

    blocked = [r for r in in_frag if r["sweep_state"] == "blocked"]
    sole = Counter()
    co = Counter()
    for r in blocked:
        ks = sorted(r["sweep_detail"])
        if len(ks) == 1:
            sole[ks[0]] += 1
        else:
            co["+".join(ks)] += 1

    all_seven = [r for r in in_frag if r["sweep_state"] == "all-seven"]
    return {
        "lex_out": lex_out, "lex_out_by_gate": lex_out_by_gate,
        "refused": refused, "refused_by_reason": refused_by_reason,
        "blocked": blocked, "sole": sole, "co": co,
        "all_seven": all_seven,
    }


def render(recs, rows, g, covered0, steps, remaining_ids, args) -> list[str]:
    lines = []

    def w(s=""):
        lines.append(s)

    w("# The MBPP-DFY 164: lexical, lifter and sweep, joined")
    w()
    w("Generated by `t/mbpp_lifter_census.py`. Answers ROADMAP 13.1's open")
    w("half: the gate order over the 164 on the LIFTER side, and where it")
    w("parts from the lexical one (`COVERAGE-mbpp-dfy.md`,")
    w("`t/mbpp_gate_order.py`). Three committed sources, joined by file and")
    w("by the sweep's own row-naming convention; no kernel run here.")
    w()
    n_all_seven_total = sum(1 for r in rows if r["sweep_state"] == "all-seven")
    n_all_seven_infrag = sum(1 for r in rows
                              if r["sweep_state"] == "all-seven" and r["in_fragment"])
    n_all_seven_outfrag = n_all_seven_total - n_all_seven_infrag
    w("Headline: %d of the 164 read verified/refuted in all seven kernels"
      % n_all_seven_total)
    w("(WS-16.2 wants 82). %d of those %d are lexically in fragment; %d are"
      % (n_all_seven_infrag, n_all_seven_total, n_all_seven_outfrag))
    w("not (the reverse disagreement, named at the bottom of this page).")
    w("The lifter-side greedy below starts from the %d, since its"
      " population is the in-fragment rows only." % n_all_seven_infrag)
    w()
    w("## One row per program (%d)" % len(rows))
    w()
    w("Lexical: `in fragment` or the primary lexical gate that blocks it")
    w("(earliest in `coverage_census.GAPS` order among the ones it carries).")
    w("Lifter: `lifted`, `refused:<name>` (its own first-refusal reading, a")
    w("LOWER bound the same way `mbpp_gate_order.py`'s histogram is one), or")
    w("`no-record`. Sweep: `all seven`, the blocking kernel cell(s), `n/a`")
    w("when the lifter never reached a check, or `not-swept` when a lifted")
    w("method has no row in `COVERAGE-lifted-785.md`.")
    w()
    w("| id | name | lexical | lifter | sweep | next move |")
    w("|---|---|---|---|---|---|")
    for r in rows:
        lex = "in fragment" if r["in_fragment"] else (r["primary_gap"] or "?")
        if r["lifter_status"] == "lifted":
            lif = "lifted"
        elif r["lifter_status"] == "refused":
            lif = "refused:" + r["lifter_reason"]
        else:
            lif = "no-record"
        if r["sweep_state"] == "all-seven":
            swp = "all seven"
        elif r["sweep_state"] == "blocked":
            swp = ", ".join("%s=%s" % (k, v) for k, v in sorted(r["sweep_detail"].items()))
        elif r["sweep_state"] == "not-swept":
            swp = "not-swept"
        else:
            swp = "n/a"
        w("| %s | %s | %s | %s | %s | %s |"
          % (r["task_id"], r["name"], lex, lif, swp, next_move(r)))

    w()
    w("## Groups")
    w()
    w("| group | count |")
    w("|---|---:|")
    w("| lexically out | %d |" % len(g["lex_out"]))
    w("| in fragment, refused by the lifter | %d |" % len(g["refused"]))
    w("| lifted, not all seven | %d |" % len(g["blocked"]))
    w("| all seven | %d |" % len(g["all_seven"]))
    w("| total | %d |" % len(rows))
    w()
    w("### Lexically out, by gate (primary gate only, so this partitions the group)")
    w()
    w("| gate | count |")
    w("|---|---:|")
    for gate, n in g["lex_out_by_gate"].most_common():
        w("| %s | %d |" % (gate, n))
    w()
    w("### In fragment but refused by the lifter, by refusal name")
    w()
    w("| refusal | count |")
    w("|---|---:|")
    for reason, n in g["refused_by_reason"].most_common():
        w("| %s | %d |" % (reason, n))
    w()
    w("### Lifted but not all seven, by blocker")
    w()
    w("| blocker | count |")
    w("|---|---:|")
    for k, n in g["sole"].most_common():
        w("| %s (sole) | %d |" % (k, n))
    for k, n in g["co"].most_common():
        w("| %s (co-blocked) | %d |" % (k, n))

    w()
    w("## The greedy order on the LIFTER side")
    w()
    w("Population: the %d rows the census already calls in fragment. Items:"
      % sum(1 for r in rows if r["in_fragment"]))
    w("a lifter refusal name closed, or one kernel's sole-blocked cells")
    w("closed. Lexical gates are not items here; a lexically-out row is out")
    w("of scope for this curve (see `mbpp_gate_order.py`'s curve for that).")
    w()
    w("Starting point: %d of those already read all seven." % covered0)
    w()
    w("| step | change | newly unlocked | cumulative |")
    w("|---|---|---:|---:|")
    hit = None
    for i, (item, n, cum) in enumerate(steps, 1):
        w("| %d | %s | %d | %d |" % (i, item, n, cum))
        if hit is None and cum >= BAR:
            hit = (i, item, cum)
    w()
    if hit:
        w("Reaches WS-16.2's bar of %d at step %d, on closing `%s` (%d)."
          % (BAR, hit[0], hit[1], hit[2]))
        head = steps[:hit[0]]
        w()
        w("Greedy head: " + "; ".join(
            "%s (+%d)" % (it, n) for it, n, _ in head))
        w()
        w("Distance to %d from the measured %d: %d change(s) by name: %s."
          % (BAR, covered0, hit[0],
             ", ".join(it for it, _, _ in head)))
    else:
        w("Never reaches WS-16.2's bar of %d; %d rows have no closeable item"
          % (BAR, len(remaining_ids)))
        w("(no-record or not-swept, outside this curve's vocabulary).")

    w()
    w("## Where the two orders part")
    w()
    n_in_frag = sum(1 for r in rows if r["in_fragment"])
    n_still_blocked = n_in_frag - covered0
    w("`COVERAGE-mbpp-dfy.md`'s lexical curve treats \"in fragment\" as the")
    w("finish line: it reaches 114 of 164 at its first step and 100% of 164")
    w("by step 16. But of the %d rows already in fragment (gap set empty,"
      % n_in_frag)
    w("nothing left to lex), only %d read all seven kernels here; the other"
      % covered0)
    w("%d are refused by the lifter for a reason no lexical gate names, or"
      % n_still_blocked)
    w("lifted but blocked by a kernel. Every row in the \"in fragment,")
    w("refused by the lifter\" and \"lifted but not all seven\" groups above")
    w("is exactly this: the lexical curve already marks it done, and the")
    w("lifter or a kernel is the real remaining gate. None of the lexical")
    w("gates in `COVERAGE-mbpp-dfy.md`'s table would move any of these %d"
      % n_still_blocked)
    w("rows; they need a lifter row or a kernel fix instead.")
    w()
    out_but_seven = [r for r in rows
                     if r["sweep_state"] == "all-seven" and not r["in_fragment"]]
    if out_but_seven:
        w("A reverse disagreement, %d rows: the census calls these lexically"
          % len(out_but_seven))
        w("out (a gap it still names), yet the lifter and all seven kernels")
        w("already cleared them -- lexical detection is approximate")
        w("(`coverage_census.py` says so of itself) and can over-flag a gap")
        w("a program does not actually need at runtime. Named: "
          + ", ".join(sorted((r["task_id"] for r in out_but_seven), key=int))
          + ".")

    return lines


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--lift", type=Path, default=DEFAULT_LIFT)
    ap.add_argument("--sweep", type=Path, default=DEFAULT_SWEEP)
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args(argv)

    recs = mbpp_gate_order.census_records()
    if not recs:
        print("no census.json; see mbpp_gate_order.py for the same check")
        return 1
    verdicts = mbpp_gate_order.lifter_verdicts(args.lift)
    sweep = load_sweep(args.sweep)

    rows = build_rows(recs, verdicts, args.lift, sweep)
    g = groups(rows)
    covered0, steps, remaining_ids = greedy_lifter(rows)

    lines = render(recs, rows, g, covered0, steps, remaining_ids, args)
    text = "\n".join(lines) + "\n"
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8", newline="\n")
        print("wrote %s" % args.out)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
